services:
  emass-ai-middelware:
    container_name: emass-ai-middelware
    image: emass-ai-middelware:0.0.0
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    volumes:
      - ./workspace:/app
    environment:
      - TZ=Asia/Seoul
    #command: python3 /app/kafka_worker.py
    command: tail -f /dev/null
    restart: always